FORMAT: X-1A
HOST: https://repos.api.brightcove.com/v1

# Brightcove Delivery System API v1

The Delivery System APIs allow for the management and deployment of a group of files, called a repository.  These files are managed through REST APIs and through git.  These files are delivered, on every "git push", to players.brightcove.com.

If you haven't gone through the <a href="//docs.brightcove.com/en/video-cloud/players/guides/playertour.html">player tour</a>, it's highly suggested you e start there.  You'll get security set up, learn some of the basics of the system, and then be ready to dive in further here.

## Service URL

The service URL for the Delivery System API is:

    https://repos.api.brightcove.com/v1

# Group Configurations

## Retrieving Repositories [/accounts/{accountId}/repos]

### GET

This will list the details for all repos in an account

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}

+ Response 200

    + Body

            {
              "items": [{
                "name": "009bc3a8-bb3f-4f94-ae9c-8e9161dc0072_af909574-1b95-4167-8f5a-81939725e843",
                "public_url": "http://players.brightcove.com/1507807800001/009bc3a8-bb3f-4f94-ae9c-8e9161dc0072_af909574-1b95-4167-8f5a-81939725e843"
              }, {
                "name": "009bc3a8-bb3f-4f94-ae9c-8e9161dc0072_default",
                "public_url": "http://players.brightcove.com/1507807800001/009bc3a8-bb3f-4f94-ae9c-8e9161dc0072_default"
              }, {
                "name": "0181ea5c-5b4d-46f5-bae9-c16b092c20d3_8fdf315d-7a7c-401a-b46a-895fa9835164",
                "public_url": "http://players.brightcove.com/1507807800001/0181ea5c-5b4d-46f5-bae9-c16b092c20d3_8fdf315d-7a7c-401a-b46a-895fa9835164"
              }, {
                "name": "0181ea5c-5b4d-46f5-bae9-c16b092c20d3_default",
                "public_url": "http://players.brightcove.com/1507807800001/0181ea5c-5b4d-46f5-bae9-c16b092c20d3_default"
              }, {
                "name": "018451f7-40d0-41e2-8c41-72da8499ecf7_default",
                "public_url": "http://players.brightcove.com/1507807800001/018451f7-40d0-41e2-8c41-72da8499ecf7_default"
              }, {
                "name": "028f4f4f-5487-44c6-ad91-678421cd3d9a_default",
                "public_url": "http://players.brightcove.com/1507807800001/028f4f4f-5487-44c6-ad91-678421cd3d9a_default"
              }, {
                "name": "0464dbd0-2f9d-4fb2-a44a-a9c7cbd0b88d_878aff8f-5e67-4a10-8966-4f89c7c1b799",
                "public_url": "http://players.brightcove.com/1507807800001/0464dbd0-2f9d-4fb2-a44a-a9c7cbd0b88d_878aff8f-5e67-4a10-8966-4f89c7c1b799"
              }],
              "item_count": 7
            }

## Retrieving, Creating and Deleting a Repository [/accounts/{accountId}/repos/{repoName}]

### GET

This will retrieve the details for a single repository

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    
    + repoName (required string `MyRepoName`) ... The name of the repo for which to list details

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}

+ Response 200

    + Body

            { "name": "[repo name]", "public_url": "[public_url]" }

### PUT

This will create a single repository, if it does not exist. A response of 200 means the repository already existed. A response of 201 means repository was successfully created.

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    
    + repoName (required string `MyRepoName`) ... The name of the repo for which to list details 


+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}
    
+ Response 200

    + Body
    
            { "name": "[repo name]", "public_url": "[public_url]" }

+ Response 201

    + Body
    
            { "name": "[repo name]", "public_url": "[public_url]" }
            
                    
### DELETE

This will delete a single repository

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    
    + repoName (required string `MyRepoName`) ... The name of the repo to delete 

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body
    
            {}

+ Response 200

    + Body    

            Successfully deleted repo MyRepoName.