FORMAT: X-1A
HOST: https://repos.api.brightcove.com/v1

# Brightcove Delivery System API v1

The Delivery System APIs allow for the management and deployment of a group of files, called a repository.  These files are managed through REST APIs and through git.  These files are delivered, on every "git push", to players.brightcove.com.

If you haven't gone through the <a href="http://docs.brightcove.com/en/video-cloud/player-management/guides/player-mgmt-quick-start.html">Quick Start to Player Management</a>, it's highly suggested you start there.  You'll get security set up, learn some of the basics of the system, and then be ready to dive in further here.

## Base URL

The base URL for the Delivery System API is:

    https://repos.api.brightcove.com/v1

# Group View Repos

Retrieve all repositories for an account

## GET Repositories [/accounts/{accountId}/repos]

### GET

This will list the details for all repos in an account

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}

+ Response 200

    + Body

            {
              "items": [
              {
                "name": "009bc3a8-bb3f-4f94-ae9c-8e9161dc0072_af909574-1b95-4167-8f5a-81939725e843",
                "public_url": "http://players.brightcove.net/1507807800001/009bc3a8-bb3f-4f94-ae9c-8e9161dc0072_af909574-1b95-4167-8f5a-81939725e843",
                "repo_url": "https://repos.api.brightcove.com/v1/accounts/1507807800001/repos/009bc3a8-bb3f-4f94-ae9c-8e9161dc0072_af909574-1b95-4167-8f5a-81939725e843"
              },
              {
                "name": "009bc3a8-bb3f-4f94-ae9c-8e9161dc0072_default",
                "public_url": "http://players.brightcove.net/1507807800001/009bc3a8-bb3f-4f94-ae9c-8e9161dc0072_default",
                "repo_url": "https://repos.api.brightcove.com/v1/accounts/1507807800001/repos/009bc3a8-bb3f-4f94-ae9c-8e9161dc0072_default"
              },
              ...
              {
                "name": "myRepoName",
                "public_url": "http://players.brightcove.net/1507807800001/myRepoName",
                "repo_url": "https://repos.api.brightcove.com/v1/accounts/1507807800001/repos/myRepoName"
              },
              {
                "name": "repoTest",
                "public_url": "http://players.brightcove.net/1507807800001/repoTest",
                "repo_url": "https://repos.api.brightcove.com/v1/accounts/1507807800001/repos/repoTest"
              },
              {
                "name": "testRepo",
                "public_url": "http://players.brightcove.net/1507807800001/testRepo",
                "repo_url": "https://repos.api.brightcove.com/v1/accounts/1507807800001/repos/testRepo"
              }],
              "item_count": 282
            }

# Group Manipulate Single Repo

Retrieve, create and delete a single repo

## GET/PUT to Create/Delete Single Repo [/accounts/{accountId}/repos/{repoName}]

### GET

This will retrieve the details for a single repository

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    
    + repoName (required string `MyRepoName`) ... The name of the repo for which to list details

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}

+ Response 200

    + Body

            { "name": "[repo name]", "public_url": "[public_url]" }

### PUT

This will create a single repository, if it does not exist. A response of 200 means the repository already existed. A response of 201 means repository was successfully created.

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    
    + repoName (required string `MyRepoName`) ... The name of the repo for which to list details 


+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}
    
+ Response 200

    + Body
    
            { "name": "[repo name]", "public_url": "[public_url]" }

+ Response 201

    + Body
    
            { "name": "[repo name]", "public_url": "[public_url]" }
            
                    
### DELETE

This will delete a single repository

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    
    + repoName (required string `MyRepoName`) ... The name of the repo to delete 

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body
    
            {}

+ Response 200

    + Body    

            Successfully deleted repo MyRepoName.